FROM node:lts-alpine

ENV LT_SERVER_URL=""
ENV LT_SUBDOMAIN=""

RUN npm install -g localtunnel

ENTRYPOINT \
  if [ ! -z "$LT_SUBDOMAIN" ]; then \
    /usr/local/bin/lt --host ${LT_SERVER_URL} --port 80 --subdomain ${LT_SUBDOMAIN} --local-host nginx ; \
  else \
    echo "localtunnel is disabled, exiting" && exit 0 ; \
  fi
