FROM node:lts-alpine

RUN npm install -g localtunnel
ENV LT_SERVER_URL=""
ENV LT_SUBDOMAIN=""

ENTRYPOINT /usr/local/bin/lt --host ${LT_SERVER_URL} --port 80 --subdomain ${LT_SUBDOMAIN} --local-host nginx
